version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  redis:
    container_name: customer_loyalty_redis
    image: redis
    restart: always
    ports:
      - 8888:6379
    volumes:
      - redisvol:/data

volumes:
  redisvol:
    driver: local
  mongo_data: {}